stages:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    metrics:
    - metrics_train.json:
        cache: false
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    metrics:
    - metrics.json:
        cache: false
  stage3:
    cmd: python src/stage3.py
    deps:
    - src/stage3.py
    params:
    - train.batch_size
    - train.dropout
    - train.hidden_units
    - train.lr
    - train.num_epochs
    metrics:
    - stage3_metrics.json
